### ISSUE TITLE
Incorrect format because of the scan order

### ISSUE THREAD

**Issue by ocarreterom** [basecamp/local_time#92]
> I18n.t("time.formats.#{format}"), I18n.t("date.formats.#{format}"), Time::DATE_FORMATS[format], and Date::DATE_FORMATS[format] will be scanned (in that order) for your format.

According to this behavior a `Date` object will be formatted with time formats.

```yml
en:
  time:
    formats:
      default: '%H'
  date:
    formats:
      default: '%a'
```

```erb
<%= local_date(Date.today, format: :default) %> # will be formatted as time
```
